  auth-server:

    grpc:
      port : 8040

    jdbc :
      driverClassName : org.postgresql.Driver
      host: 192.168.63.15
      port : 15432
      name : sampledb
      user : userUD6
      password : fXrgrCUiw7rXOXLe
      url : jdbc:postgresql://${auth-server.jdbc.host}:${auth-server.jdbc.port}/${auth-server.jdbc.name}

    tokenServiceProp:
      tokenValidSecond : 28800

  server :
    port : 8081
    servlet :
      context-path : /auth

  spring:
    liquibase:
      change-log: classpath:/db/changelog/db.changelog-master.xml
    devtools:
      restart:
        enabled: false
      livereload:
        enabled: true
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:postgresql://${auth-server.jdbc.host}:${auth-server.jdbc.port}/${auth-server.jdbc.name}
      name:
      username: ${auth-server.jdbc.user}
      password: ${auth-server.jdbc.password}
      hikari:
        idle-timeout: 90000
    jpa:
      open-in-view: true
      database-platform: org.hibernate.dialect.PostgreSQL94Dialect
      database: POSTGRESQL
      show-sql: true
      properties:
        hibernate.format_sql: true
        hibernate.use_sql_comments: true
        hibernate.temp.use_jdbc_metadata_defaults: false
        hibernate.hbm2ddl.auto: update