spring:
    datasource:
        url: ${PG_URL}
        username: ${PG_USERNAME}
        password: ${PG_PASSWORD}

auth-server:
    grpc:
        port : 8030
    tokenServiceProp:
        tokenValidSecond : 28800