spring:
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.xml
    devtools:
        restart:
            enabled: false
            livereload:
                enabled: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        name:
        hikari:
            idle-timeout: 90000

    jpa:
        open-in-view: true
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        database: POSTGRESQL
        show-sql: true
    properties:
        hibernate.format_sql: true
        hibernate.use_sql_comments: true
        hibernate.temp.use_jdbc_metadata_defaults: false
        hibernate.hbm2ddl.auto: update


server:
    port: 8081
    servlet :
        context-path : /auth
