spring:
    datasource:
        url: jdbc:postgresql://192.168.63.15:15432/sampledb
        username: userUD6
        password: fXrgrCUiw7rXOXLe

auth-server:
    grpc:
        port : 8040
    tokenServiceProp:
        tokenValidSecond : 28800

    ldap:
      url: ldap://192.168.10.252/dc=egar,dc=egartech,dc=com
      userDnPattern: login={0}
      passwordAttribute: userPassword
      groupSearchBase: ou=groups
